scaffolds/dva-example-user-dashboard/index.yml

url: 'https://github.com/dvajs/dva-example-user-dashboard/'
name: dva-example-user-dashboard
git_url: 'git://github.com/dvajs/dva-example-user-dashboard.git'
chineseName: dva-example-user-dashboard
author: dvajs
description: "\uD83D\uDC72 \uD83D\uDC6C \uD83D\uDC68‍\uD83D\uDC69‍\uD83D\uDC67 \uD83D\uDC68‍\uD83D\uDC69‍\uD83D\uDC66‍\uD83D\uDC66"
version: 0.0.1
industry: react
source: npm

add scaffold dva-example-user-dashboard to antd scaffold

---

data/dva-example-user-dashboard/scaffold.json
scaffolds/chat/index.yml

url: 'https://github.com/RaoHai/chat'
name: chat
git_url: 'git://github.com/RaoHai/chat.git'
chineseName: chat
author: RaoHai
description: 'A Chat Scaffold based on antd and dva:'
version: 0.0.1
industry: react
source: npm

add scaffold chat to antd scaffold

---

scaffolds/react-antd/index.yml

Reverts ant-design/scaffold-market#10

Revert "add scaffold react-antd to antd scaffold"

---

scaffolds/dvajs/dva-example-user-dashboard/index.yml

- Name: `dvajs/dva-example-user-dashboard`
- Url: `git://github.com/dvajs/dva-example-user-dashboard.git`

Add template dvajs/dva-example-user-dashboard to the market

---

scaffolds/dva-example-user-dashboard/index.yml

- Name: `dva-example-user-dashboard`
- Url: `git://github.com/dvajs/dva-example-user-dashboard.git`

Add template dva-example-user-dashboard to the market

---

scaffolds/react-antd-admin/index.yml

- Name: `react-antd-admin`
- Url: `git://github.com/fireyy/react-antd-admin.git`

Add react-antd-admin to the market

---

scaffolds/antd-admin-boilerplate/index.yml

- Name: `antd-admin-boilerplate`
- Url: `git://github.com/myqianlan/antd-admin-boilerplate.git`

Add antd-admin-boilerplate to the market

---

scaffolds/ui/index.yml

- Name: `ui`
- Url: `git://github.com/tianzx/ui.git`

Add ui to the market

---

scaffolds/react-antd/index.yml

- Name: `react-antd`
- Url: `git://github.com/sosout/react-antd.git`

Add react-antd to the market

---

scaffolds/react-antd-demo/index.yml

- Name: `react-antd-demo`
- Url: `git://github.com/luozhihao/react-antd-demo.git`

Add react-antd-demo to the market

---

scaffolds/antd-redux/index.yml

- Name: `antd-redux`
- Url: `git://github.com/guox191/antd-redux.git`

Add antd-redux to the market

---

scaffolds/react-start-kit/index.yml

- Name: `react-start-kit`
- Url: `git://github.com/jovey-zheng/react-start-kit.git`

Add react-start-kit to the market

---

scaffolds/ts-dva/index.yml

- Name: `ts-dva`
- Url: `git://github.com/huang6349/ts-dva.git`

Add ts-dva to the market

---

scaffolds/star-initReact-example/index.yml

- Name: `star-initReact-example`
- Url: `git://github.com/pookpal/star-initReact-example.git`

Add star-initReact-example to the market

---

scaffolds/react-redux-antd-okoala/index.yml

- Name: `react-redux-antd-okoala`
- Url: `git://github.com/okoala/react-redux-antd.git`

Add react-redux-antd-okoala to the market

---

scaffolds/reactSPA/index.yml

- Name: `reactSPA`
- Url: `git://github.com/JasonBai007/reactSPA.git`

Add reactSPA to the market

---

scaffolds/react-scaffold/index.yml

- Name: `react-scaffold`
- Url: `git://github.com/starriv/react-scaffold.git`

Add react-scaffold to the market

---

scaffolds/react-redux-universal/index.yml

- Name: `react-redux-universal`
- Url: `git://github.com/subenksaha/react-redux-universal.git`

Add react-redux-universal to the market

---

scaffolds/blogVue/index.yml

- Name: `blogVue`
- Url: `git://github.com/xumjs8623/blogVue.git`

Add blogVue to the market

---

scaffolds/dva-antd-starter/index.yml

- Name: `dva-antd-starter`
- Url: `git://github.com/xlsdg/dva-antd-starter.git`

Add dva-antd-starter to the market

---

scaffolds/dva-antd-mobile-starter/index.yml

- Name: `dva-antd-mobile-starter`
- Url: `git://github.com/xlsdg/dva-antd-mobile-starter.git`

Add dva-antd-mobile-starter to the market

---

scaffolds/ui/index.yml

Re-deploy ui

---

scaffolds/react-molin/index.yml

- Name: `react-molin`
- Url: `git://github.com/Molin123/react-molin.git`

Add react-molin to the market

---

scaffolds/dva-admin/index.yml

- Name: `dva-admin`
- Url: `git://github.com/pmg1989/dva-admin.git`

Add dva-admin to the market

---

scaffolds/fanpianAdmin/index.yml

- Name: `fanpianAdmin`
- Url: `git://github.com/douglasvegas/fanpianAdmin.git`

Add fanpianAdmin to the market

---

scaffolds/dva-admin/index.yml

Re-deploy dva-admin

---

scaffolds/react-component-lab/index.yml

- Name: `react-component-lab`
- Url: `git://github.com/leesx/react-component-lab.git`

Add react-component-lab to the market

---

scaffolds/antd-auto/index.yml

- Name: `antd-auto`
- Url: `git://github.com/niyingfeng/antd-auto.git`

Add antd-auto to the market

---

scaffolds/Da/index.yml

- Name: `Da`
- Url: `git://github.com/liumin1128/CourseManagementSystem.git`

Add Da to the market

---

scaffolds/dva-ant-admin/index.yml

- Name: `dva-ant-admin`
- Url: `git://github.com/Mulgore/dva-ant-admin.git`

Add dva-ant-admin to the market

---

scaffolds/little-a-dashboard/index.yml

- Name: `little-a-dashboard`
- Url: `git://github.com/huzzbuzz/little-a-dashboard.git`

Add little-a-dashboard to the market

---

scaffolds/react-qs/index.yml

- Name: `react-qs`
- Url: `git://github.com/leesx/react-qs.git`

Add react-qs to the market

---

scaffolds/typescript-react-hot-reload/index.yml

- Name: `typescript-react-hot-reload`
- Url: `git://github.com/chunliu/typescript-react-hot-reload.git`

Add typescript-react-hot-reload to the market

---

scaffolds/ng-alain/index.yml

- Name: `ng-alain`
- Url: `git://github.com/cipchk/ng-alain.git`

Add ng-alain to the market

---

scaffolds/sls-admin/index.yml

- Name: `sls-admin`
- Url: `git://github.com/sailengsi/sls-admin.git`

Add sls-admin to the market

---

scaffolds/ReactAntd/index.yml

- Name: `ReactAntd`
- Url: `git://github.com/2425358736/ReactAntd.git`

Add ReactAntd to the market

---

scaffolds/mk-demo/index.yml

- Name: `mk-demo`
- Url: `git://github.com/ziaochina/mk-demo.git`

Add mk-demo to the market

---

scaffolds/Maple/index.yml

- Name: `Maple`
- Url: `git://github.com/liujian10/myBlog.git`

Add Maple to the market

---

scaffolds/kenote-react-admin/index.yml

- Name: `kenote-react-admin`
- Url: `git://github.com/thondery/kenote-react-admin.git`

Add kenote-react-admin to the market

---

scaffolds/ant-design-pro/index.yml

- Name: `ant-design-pro`
- Url: `git://github.com/ant-design/ant-design-pro.git`

Add ant-design-pro to the market

---

scaffolds/Maple/index.yml

Re-deploy Maple

---

scaffolds/react-mobx-antd-boilerplate/index.yml

- Name: `react-mobx-antd-boilerplate`
- Url: `git://github.com/moxun33/react-mobx-antd-boilerplate.git`

Add react-mobx-antd-boilerplate to the market

---

scaffolds/vue-taobao/index.yml

- Name: `vue-taobao`
- Url: `git://github.com/sosout/vue-taobao.git`

Add vue-taobao to the market

---

scaffolds/vue2-element/index.yml

- Name: `vue2-element`
- Url: `git://github.com/sosout/vue2-element.git`

Add vue2-element to the market

---

scaffolds/dva-boot/index.yml

- Name: `dva-boot`
- Url: `git://github.com/LANIF-UI/dva-boot.git`

Add dva-boot to the market

---

scaffolds/create-react-app-antd-mobile-starter/index.yml

- Name: `create-react-app-antd-mobile-starter`
- Url: `git://github.com/xlsdg/create-react-app-antd-mobile-starter.git`

Add create-react-app-antd-mobile-starter to the market

---

scaffolds/dva-antd-typescript-starter/index.yml

- Name: `dva-antd-typescript-starter`
- Url: `git://github.com/xlsdg/dva-antd-typescript-starter.git`

Add dva-antd-typescript-starter to the market

---

scaffolds/create-react-app-antd-starter/index.yml

- Name: `create-react-app-antd-starter`
- Url: `git://github.com/xlsdg/create-react-app-antd-starter.git`

Add create-react-app-antd-starter to the market

---

scaffolds/bird-front/index.yml

- Name: `bird-front`
- Url: `git://github.com/liuxx001/bird-front.git`

Add bird-front to the market

---

scaffolds/react-webpack-boilerplate/index.yml

- Name: `react-webpack-boilerplate`
- Url: `git://github.com/amostap/react-webpack-boilerplate.git`

Add react-webpack-boilerplate to the market

---

scaffolds/React-SPA/index.yml

- Name: `React-SPA`
- Url: `git://github.com/allan2coder/React-SPA.git`

Add React-SPA to the market

---

scaffolds/VUE2-SPA-Tutorial/index.yml

- Name: `VUE2-SPA-Tutorial`
- Url: `git://github.com/allan2coder/VUE2-SPA-Tutorial.git`

Add VUE2-SPA-Tutorial to the market

---

scaffolds/react-ame-admin/index.yml

- Name: `react-ame-admin`
- Url: `git://github.com/fachilles/react-ame-admin.git`

Add react-ame-admin to the market

---

scaffolds/vue-mobile/index.yml

- Name: `vue-mobile`
- Url: `git://github.com/GavinZhuLei/vue-mobile.git`

Add vue-mobile to the market

---

scaffolds/dva-antd-admin/index.yml

- Name: `dva-antd-admin`
- Url: `git://github.com/bowencool/dva-antd-admin.git`

Add dva-antd-admin to the market

---

scaffolds/inferno-mobile/index.yml

- Name: `inferno-mobile`
- Url: `git://github.com/leesx/inferno-mobile.git`

Add inferno-mobile to the market

---

scaffolds/ts_react_mobx/index.yml

- Name: `ts_react_mobx`
- Url: `git://github.com/dreambo8563/ts_react_mobx.git`

Add ts_react_mobx to the market

---

scaffolds/parcel-start-kit/index.yml

- Name: `parcel-start-kit`
- Url: `git://github.com/goWrongWay/parcel-start-kit.git`

Add parcel-start-kit to the market

---

scaffolds/umi-antd-pro/index.yml

- Name: `umi-antd-pro`
- Url: `git://github.com/xiaohuoni/umi-antd-pro.git`

Add umi-antd-pro to the market

---

scaffolds/dva-umi/index.yml

- Name: `dva-umi`
- Url: `git://github.com/xiaohuoni/dva-umi.git`

Add dva-umi to the market

---

scaffolds/dva-umi-mobile/index.yml

- Name: `dva-umi-mobile`
- Url: `git://github.com/xiaohuoni/dva-umi-mobile.git`

Add dva-umi-mobile to the market

---

scaffolds/dva-boot-admin/index.yml

- Name: `dva-boot-admin`
- Url: `git://github.com/LANIF-UI/dva-boot-admin.git`

Add dva-boot-admin to the market

---

scaffolds/typerx/index.yml

- Name: `typerx`
- Url: `git://github.com/vellengs/typerx.git`

Add typerx to the market

---

scaffolds/react-router4-redux-express-webpack4/index.yml

- Name: `react-router4-redux-express-webpack4`
- Url: `git://github.com/sktony6260/react-router4-redux-express-webpack4.git`

Add react-router4-redux-express-webpack4 to the market

---

scaffolds/d2-admin/index.yml

- Name: `d2-admin`
- Url: `git://github.com/d2-projects/d2-admin.git`

Add d2-admin to the market

---

scaffolds/ant-design-pro/index.yml

Reverts ant-design/scaffold-market#210

Revert "Re-deploy ant-design-pro"

---

scaffolds/dva-ant-admin/index.yml

Re-deploy dva-ant-admin

---

scaffolds/mobxSpa/index.yml

- Name: `mobxSpa`
- Url: `git://github.com/Tianlikai/mobxSpa.git`

Add mobxSpa to the market

---

scaffolds/react-app-reflux/index.yml

- Name: `react-app-reflux`
- Url: `git://github.com/missra-kit/react-app-reflux.git`

Add react-app-reflux to the market

---

scaffolds/my-blog/index.yml

- Name: `my-blog`
- Url: `git://github.com/1degrees/my-blog.git`

Add my-blog to the market

---

scaffolds/Library-reservation/index.yml

- Name: `Library-reservation`
- Url: `git://github.com/MKitty/Library-reservation.git`

Add Library-reservation to the market

---

scaffolds/ts-react-webpack/index.yml

- Name: `ts-react-webpack`
- Url: `git://github.com/YDJ-FE/ts-react-webpack.git`

Add ts-react-webpack to the market

---

scaffolds/create-react-app-antd/index.yml

- Name: `create-react-app-antd`
- Url: `git://github.com/ant-design/create-react-app-antd.git`

Add create-react-app-antd to the market

---

scaffolds/react-app/index.yml

- Name: `react-app`
- Url: `git://github.com/pdsuwwz/react-app.git`

Add react-app to the market

---

scaffolds/blog3.x-mux-club/index.yml

- Name: `blog3.x-mux-club`
- Url: `git://github.com/PhotoArtLife/blog3.x-mux-club.git`

Add blog3.x-mux-club to the market

---

scaffolds/eshop-user/index.yml

- Name: `eshop-user`
- Url: `git://github.com/Monkhjargal/eshop-user.git`

Add eshop-user to the market

---

scaffolds/acgnfuns-app/index.yml

- Name: `acgnfuns-app`
- Url: `git://github.com/sppsun/acgnfuns-app.git`

Add acgnfuns-app to the market

---

scaffolds/wallpaper-app/index.yml

- Name: `wallpaper-app`
- Url: `git://github.com/sppsun/wallpaper-app.git`

Add wallpaper-app to the market

---

scaffolds/acgnfuns-mobile/index.yml

- Name: `acgnfuns-mobile`
- Url: `git://github.com/sppsun/acgnfuns-mobile.git`

Add acgnfuns-mobile to the market

---

scaffolds/webpack4-react-redux-router-antd/index.yml

- Name: `webpack4-react-redux-router-antd`
- Url: `git://github.com/xiaopingzhang0207/webpack4-react-redux-router-antd.git`

Add webpack4-react-redux-router-antd to the market

---

scaffolds/d2-admin/index.yml

如有需要，请将 https://qiniucdn.fairyever.com/20190226161826.png 此图片转存到 scaffold-market 项目使用的 CDN。

Update D2Admin cover picture

---

scaffolds/generator-chrome-extension/index.yml

- Name: `generator-chrome-extension`
- Url: `git://github.com/yeoman/generator-chrome-extension.git`

Add generator-chrome-extension to the market

---

scaffolds/Sword/index.yml

- Name: `Sword`
- Url: `git://github.com/chillzhuang/Sword.git`

Add Sword to the market

---

scaffolds/create-umi/index.yml

- Name: `create-umi`
- Url: `git://github.com/umijs/create-umi.git`

Add create-umi to the market

---

scaffolds/ElementUIAdmin/index.yml

- Name: `ElementUIAdmin`
- Url: `git://github.com/xusenlin/ElementUIAdmin2.git`

Add ElementUIAdmin to the market

---

scaffolds/dashboard/index.yml

- Name: `dashboard`
- Url: `git://github.com/zce/dashboard.git`

Add dashboard to the market

---

scaffolds/antd-pro-mobx/index.yml

- Name: `antd-pro-mobx`
- Url: `git://github.com/gzgogo/antd-pro-mobx.git`

Add antd-pro-mobx to the market

---

scaffolds/d2-admin/index.yml

Re-deploy d2-admin

---

package-lock.json

chore: add package-lock.json for project

---

scaffolds/react-reactRouter-redux-antd-SPA/index.yml

- Name: `react-reactRouter-redux-antd-SPA`
- Url: `git://github.com/greenhaha/react-antd.git`

Add react-reactRouter-redux-antd-SPA to the market

---

scaffolds/ttk-app-core/index.yml

Re-deploy ttk-app-core

---

scaffolds/antd-pro-concent/index.yml

- Name: `antd-pro-concent`
- Url: `git://github.com/concentjs/antd-pro-concent.git`

Add antd-pro-concent to the market

---

scaffolds/yukino/index.yml

- Name: `yukino`
- Url: `git://github.com/Shino161/yukino.git`

Add yukino to the market

---

scaffolds/vueScaffold/index.yml

- Name: `vueScaffold`
- Url: `git://github.com/dyywork/vueScaffold.git`

Add vueScaffold to the market

---

scaffolds/antd-custom/index.yml

- Name: `antd-custom`
- Url: `git://github.com/ctq123/antd-custom.git`

Add antd-custom to the market

---

scaffolds/epee-react-admin-ts/index.yml

- Name: `epee-react-admin-ts`
- Url: `git://github.com/dobble11/epee-react-admin-ts.git`

Add epee-react-admin-ts to the market

---

scaffolds/vue-vant-template/index.yml

- Name: `vue-vant-template`
- Url: `git://github.com/hubery3721/vue-vant-template.git`

Add vue-vant-template to the market

---

scaffolds/react-scaffolding-mobx/index.yml

- Name: `react-scaffolding-mobx`
- Url: `git://github.com/xuya227939/react-scaffolding-mobx.git`

Add react-scaffolding-mobx to the market

---

scaffolds/react-scaffolding/index.yml

- Name: `react-scaffolding`
- Url: `git://github.com/xuya227939/react-scaffolding.git`

Add react-scaffolding to the market

---

scaffolds/ElementUIAdmin/index.yml

Re-deploy ElementUIAdmin

---

scaffolds/emptyd-admin-webpack/index.yml

- Name: `emptyd-admin-webpack`
- Url: `git://github.com/FreemenL/emptyd-admin-webpack.git`

Add emptyd-admin-webpack to the market

---

scaffolds/saso/index.yml

- Name: `saso`
- Url: `git://github.com/huruji/saso.git`

Add saso to the market

---

scaffolds/react-typescript-admin/index.yml

- Name: `react-typescript-admin`
- Url: `git://github.com/chachaxw/react-typescript-admin.git`

Add react-typescript-admin to the market

---

scaffolds/want/index.yml

- Name: `want`
- Url: `git://github.com/way-jm/want.git`

Add want to the market

---

scaffolds/myantdpro/index.yml

- Name: `myantdpro`
- Url: `git://github.com/hankaibo/myantdpro.git`

Add myantdpro to the market

---

scaffolds/react-admin-template/index.yml

- Name: `react-admin-template`
- Url: `git://github.com/woleicom/react-admin-template.git`

Add react-admin-template to the market

---

scaffolds/React-AntD-PWA/index.yml

- Name: `React-AntD-PWA`
- Url: `git://github.com/akshaycj/react-antd-starter.git`

Add React-AntD-PWA to the market

---

scaffolds/frontend-cli/index.yml

- Name: `frontend-cli`
- Url: `git://github.com/ashuihui/frontend-cli.git`

Add frontend-cli to the market

---

scaffolds/react-study/index.yml

- Name: `react-study`
- Url: `git://github.com/liubin915249126/react-study.git`

Add react-study to the market

---

src/models/auth.js

* fix: request public repo only
* before: 
* after:

fix: request public repos data only

---

scaffolds/react-antd-multi-tabs-admin/index.yml

- Name: `react-antd-multi-tabs-admin`
- Url: `git://github.com/hsl947/react-antd-multi-tabs-admin.git`

Add react-antd-multi-tabs-admin to the market

---

scaffolds/wedding-app/index.yml

- Name: `wedding-app`
- Url: `git://github.com/wforguo/wedding-app.git`

Add wedding-app to the market

---

scaffolds/pv-cli/index.yml

- Name: `pv-cli`
- Url: `git://github.com/yiyi17/pv-cli.git`

Add pv-cli to the market

---

scaffolds/feup/index.yml

- Name: `feup`
- Url: `git://github.com/feupjs/feup.git`

Add feup to the market

---

scaffolds/umi-antd-mobile/index.yml

- Name: `umi-antd-mobile`
- Url: `git://github.com/hqwlkj/umi-antd-mobile.git`

Add umi-antd-mobile to the market

---

scaffolds/wwvue-cli/index.yml

- Name: `wwvue-cli`
- Url: `git://github.com/vannvan/wwvue-cli.git`

Add wwvue-cli to the market

---

scaffolds/xinadmin/index.yml

- Name: `xinadmin`
- Url: `git://github.com/xiaoliu978/xinadmin.git`

Add xinadmin to the market

---

scaffolds/react-admin-web/index.yml

- Name: `react-admin-web`
- Url: `git://github.com/caihai123/react-admin-web.git`

Add react-admin-web to the market
