ant-design/scaffold-market

scaffolds/dva-hackernews/index.yml
url: 'https://github.com/dvajs/dva-hackernews'
name: dva-hackernews
git_url: 'git://github.com/dvajs/dva-hackernews.git'
chineseName: dva-hackernews
author: dvajs
description: HackerNews clone built with Dva.
version: 0.0.1
industry: react
source: npm
=> add scaffold dva-hackernews to antd scaffold

scaffolds/react-antd/index.yml
url: 'https://github.com/zhaotoday/react-antd'
name: react-antd
git_url: 'git://github.com/zhaotoday/react-antd.git'
chineseName: react-antd
author: zhaotoday
description: A boilerplate for react project based on antd. 基于 antd 的 react 项目模板。 — Edit
version: 0.0.1
industry: react
source: npm
=> add scaffold react-antd to antd scaffold

scaffolds/react-frontend-boilerplate/index.yml
- Name: `react-frontend-boilerplate`
- Url: `git://github.com/huhulab/react-frontend-boilerplate.git`
=> Add react-frontend-boilerplate to the market

scaffolds/react-redux-antd-starter/index.yml
- Name: `react-redux-antd-starter`
- Url: `git://github.com/BetaRabbit/react-redux-antd-starter.git`
=> Add react-redux-antd-starter to the market

scaffolds/react-redux-router-antd-int-cli/index.yml
- Name: `react-redux-router-antd-int-cli`
- Url: `git://github.com/KK-Lin/react-redux-router-antd-int-cli.git`
=> Add react-redux-router-antd-int-cli to the market

scaffolds/angular-material-dashboard/index.yml
- Name: `angular-material-dashboard`
- Url: `git://github.com/wangdicoder/angular-material-dashboard.git`
=> Add angular-material-dashboard to the market

scaffolds/react-redux-antdesign-webpack-starter/index.yml
- Name: `react-redux-antdesign-webpack-starter`
- Url: `git://github.com/MacKentoch/react-redux-antdesign-webpack-starter.git`
=> Add react-redux-antdesign-webpack-starter to the market

scaffolds/gt-react-scaffold/index.yml
- Name: `gt-react-scaffold`
- Url: `git://github.com/vivaxy/gt-react-scaffold.git`
=> Add gt-react-scaffold to the market

scaffolds/create-react-app-antd-typescript-starter/index.yml
- Name: `create-react-app-antd-typescript-starter`
- Url: `git://github.com/xlsdg/create-react-app-antd-typescript-starter.git`
=> Add create-react-app-antd-typescript-starter to the market

scaffolds/material-demo/index.yml
- Name: `material-demo`
- Url: `git://github.com/toolaugh/material-demo.git`
=> Add material-demo to the market

scaffolds/next-react-mobx-antd-boilerplate/index.yml
- Name: `next-react-mobx-antd-boilerplate`
- Url: `git://github.com/1degrees/next-react-mobx-antd-boilerplate.git`
=> Add next-react-mobx-antd-boilerplate to the market

scaffolds/electron-antd/index.yml
- Name: `electron-antd`
- Url: `git://github.com/lanten/electron-antd.git`
=> Add electron-antd to the market

scaffolds/ant-design-pro-vue/index.yml
- Name: `ant-design-pro-vue`
- Url: `git://github.com/sendya/ant-design-pro-vue.git`
=> Add ant-design-pro-vue to the market

scaffolds/React-cli/index.yml
- Name: `React-cli`
- Url: `git://github.com/tuiche000/React-cli.git`
=> Add React-cli to the market

scaffolds/next-antd-scafflod/index.yml
- Name: `next-antd-scafflod`
- Url: `git://github.com/luffyZh/next-antd-scafflod.git`
=> Add next-antd-scafflod to the market

scaffolds/electron-react-typescript-antd-boilerplate/index.yml
- Name: `electron-react-typescript-antd-boilerplate`
- Url: `git://github.com/CNLHC/electron-react-typescript-antd-boilerplate.git`
=> Add electron-react-typescript-antd-boilerplate to the market

scaffolds/d2-admin/index.yml
因为 https://github.com/ant-design/scaffold-market/issues/243
需要删除相关资料后重新申请收录
=> remove d2-admin

scaffolds/next-antd-scaffold/index.yml
- Name: `next-antd-scaffold`
- Url: `git://github.com/luffyZh/next-antd-scaffold.git`
=> Add next-antd-scaffold to the market

scaffolds/react-mobx-react-router-boilerplate/index.yml
- Name: `react-mobx-react-router-boilerplate`
- Url: `git://github.com/kwzm/react-mobx-react-router-boilerplate.git`
=> Add react-mobx-react-router-boilerplate to the market

scaffolds/react-mobx-antd-spa/index.yml
- Name: `react-mobx-antd-spa`
- Url: `git://github.com/lazybear1017/react-mobx-antd-router-xcf.git`
=> Add react-mobx-antd-spa to the market

scaffolds/antd-layout/index.yml
- Name: `antd-layout`
- Url: `git://github.com/1006223320/antd-layout.git`
=> Add antd-layout to the market

src/services/list.js
Changed list.json to be read from https rather than http. See[ issue # 267 ](https://github.com/ant-design/scaffold-market/issues/267)
=> Fix to Issue # 267

scaffolds/react-antd-dashboard/index.yml
- Name: `react-antd-dashboard`
- Url: `git://github.com/theeranan/react-antd-dashboard.git`
=> Add react-antd-dashboard to the market

scaffolds/ant-design-pro-plus/index.yml
- Name: `ant-design-pro-plus`
- Url: `git://github.com/theprimone/ant-design-pro-plus.git`
=> Add ant-design-pro-plus to the market

scaffolds/next-antd/index.yml
- Name: `next-antd`
- Url: `git://github.com/hqwlkj/next-antd.git`
=> Add next-antd to the market
